website_port: 3000
website_deploy_directory: c:\iisexpress\FootballPools
website_port_load_balanced_1: 4000
website_deploy_directory_load_balanced_1: c:\iisexpress\FootballPools_4000
website_port_load_balanced_2: 5000
website_deploy_directory_load_balanced_2: c:\iisexpress\FootballPools_5000
solution_name: FootballPools #just the name, no .sln extension
mvc_project: FootballPools #just the folder name, no .csproj extension
test_project: FootballPools.Tests #just the folder name, no .csproj extension
test_runner: ./packages/nspec.0.9.68/tools/NSpecRunner.exe
iis_express: C:\Program Files (x86)\IIS Express
database_name: FootballPools
database_server: (local)
